### ISSUE TITLE
Aktuelles

### ISSUE THREAD

**Issue by paulithu** [paulithu/Website_2.0.#11]
1. Richtige Dateien verlinken
2. Bei "alles rund ums Training" die Maus checken bzw beheben
3. NEWS Button neu verlinken!

**Comment by paulithu** [comment]
Design: Boxen für jede einzelne News

**Comment by paulithu** [comment]
Videos kann man nicht öffnen ! Nachschauen

**Comment by MB412** [comment]
> Videos kann man nicht öffnen ! Nachschauen

Ich habe Blessing-Kehren mal ne Email geschrieben.
