### ISSUE TITLE
Frage zu Reiter Steinbeis 

### ISSUE THREAD

**Issue by paulithu** [paulithu/Website_2.0.#13]
Sollen wir Steinbeis als extra Punkt lassen oder soll man das auf die Startseite einbauen?

Kommentiert eure Meinung

**Comment by paulithu** [comment]
Soll man solche zwei Links auch hinzufügen oder nicht ?
Also einmal den Link zu dem Profil von ihm in researchgate und einmal der link zu dem Lebenslauf (da sollte man sich auch was überlegen... PDF fanden die nicht so gut)

![Bild1](https://user-images.githubusercontent.com/93073650/164264085-29696955-ab0f-44e5-8680-3a39440bfc08.png)

**Comment by Bene-afk** [comment]
Ja, die Idee find ich gut. Evtl. mit jeweils einem Pictogramm/logo 
![researchgate-logo-freelogovectors net_](https://user-images.githubusercontent.com/92974339/164293484-dc4c0e49-e2e9-4af9-9076-c58ef028a5bb.svg)
![2275251](https://user-images.githubusercontent.com/92974339/164293599-9f16575d-f615-456d-8bfd-f3e7bd00370b.png)
