### ISSUE TITLE
Lebenslauf

### ISSUE THREAD

**Issue by paulithu** [paulithu/Website_2.0.#15]
Extra Seite für den Lebenslauf ?
Infos: Werdegang, Projekte, Abschlüsse, etc.

**Comment by paulithu** [comment]
Status: wird nachgefragt

**Comment by paulithu** [comment]
Frage- ob man das direkt an die email senden kann

**Comment by MB412** [comment]
Wir lassen den Lebenslauf erstmal so bzw machen keine extra Seite.
