### ISSUE TITLE
Emailadresse

### ISSUE THREAD

**Issue by paulithu** [paulithu/Website_2.0.#16]
Kann man die Emailadresse auf den Reitern Kontakt/Standort so verlinken, dass sich ein Emailfenster dann öffnet? oder dass diese als Link auf der Homepage vorhanden ist?

**Comment by timojenter** [comment]
> Kann man die Emailadresse auf den Reitern Kontakt/Standort so verlinken, dass sich ein Emailfenster dann öffnet? oder dass diese als Link auf der Homepage vorhanden ist?

Müsste funktionieren
