### ISSUE TITLE
Doku

### ISSUE THREAD

**Issue by paulithu** [paulithu/Website_2.0.#17]
-Gliederung erstellen
-Text anfangen

**Comment by Bene-afk** [comment]
Ich denke folgende können wir schon bearbeiten:
- Github ( Neue Struktur mit Issus usw.)
- Bewertungskritierien für uns festgelegt
- Neue Strukturierung mit Doku/Programmiere Team
- Evtl. noch das wir gelernt haben ? Mehr Fokus auf die Interaktion mit dem Auftraggeber// Mehr mit Deadlines gearbeitet usw.
- Gliederung
- Literatur Verzeichnis

**Comment by paulithu** [comment]
Gliederung und Word Datei wurde erstellt
