### ISSUE TITLE
Backup vom Code

### ISSUE THREAD

**Issue by paulithu** [paulithu/Website_2.0.#25]
Sobald du @endricha wieder zugriff zu den Servern hast, bitte sofort ein Backup vom gesamten Code machen, damit wir gesichert sind!

**Comment by endricha** [comment]
Hab jetzt mal die letzten Versionen hochgeladen die ich gefunden hatte- kann nicht garantieren, dass es die aktuellen waren, weil ich die auch Ende vllt nicht mehr in dem Ordner gespeichert, aber sonst müsst ihr leider warten bis ich wieder fit bin und zum Bahrs kann
