### ISSUE TITLE
Extras

### ISSUE THREAD

**Issue by paulithu** [paulithu/Website_2.0.#27]
-Newsletter
-Slider
-Cookies
-Vorlage Html

**Comment by paulithu** [comment]
Wurde schon nachgeschaut, ob man das Kontaktformular an die Mail von Blessing geschickt wird ?

**Comment by paulithu** [comment]
https://www.sitepoint.com/eat-those-cookies-with-jquery/#:~:text=Working%20with%20Cookies%20in%20jQuery%201%20Installing%20jquery.cookie.,manage%20cookies%20using%20jquery.cookie%2C%20a%20jQuery%20plugin.%20 

hier mal nen link zu den cookies von jquery @MB412 ...

**Comment by MB412** [comment]
Danke dir, Cookies haben wir fertig. Habs mit Js gemacht :)

**Comment by MB412** [comment]
> Wurde schon nachgeschaut, ob man das Kontaktformular an die Mail von Blessing geschickt wird ?

Nein noch nicht bzw wir müssen noch nach einem Formular schauen.

**Comment by MB412** [comment]
> https://www.sitepoint.com/eat-those-cookies-with-jquery/#:~:text=Working%20with%20Cookies%20in%20jQuery%201%20Installing%20jquery.cookie.,manage%20cookies%20using%20jquery.cookie%2C%20a%20jQuery%20plugin.%20
> 
> hier mal nen link zu den cookies von jquery @MB412 ...

Danke dir, Cookies haben wir fertig. Habs mit Js gemacht :)
