### ISSUE TITLE
Libaries

### ISSUE THREAD

**Issue by paulithu** [paulithu/Website_2.0.#7]
Die Libaries **reactjs & jquery** anschauen!

**Comment by paulithu** [comment]
Hier dazu die Websiten:
**https://reactjs.org/ 
https://jquery.com/**

**Comment by Fab1l1** [comment]
https://nextjs.org/

**Comment by paulithu** [comment]
habt ihr euch schon für eine Libary entschieden oder nehmt ihr mehrere?

**Comment by MB412** [comment]
Haben uns noch nicht festgelegt

**Comment by paulithu** [comment]
Habt ihr einen Zeitpunkt abgemacht an dem ihr diese festlegt?

**Comment by MB412** [comment]
Wir schauen, dass wir es diese Woche klären. 👍

**Comment by paulithu** [comment]
Am Besten dann die Entscheidung als Kommentar hier schreiben und dann schließen

**Comment by paulithu** [comment]
https://getbootstrap.com/
