### ISSUE TITLE
Präsentation für das Milestone Meeting Mai

### ISSUE THREAD

**Issue by paulithu** [paulithu/Website_2.0.#9]
Eine kurze Präsi erstellen über den Stand, was wir bis jetzt haben und wie der folgende Plan aussieht.

**Comment by Bene-afk** [comment]
Ich hab gerade geschaut, dass Milestone Meeting jetzt spontan nicht gefunden. Es gibt glaub noch kein Termin. Es steht nur "Mai: Meilenstein Meeting" in dem moddel dokument.
